created todo list
vitorcorreasx/TODO-LIST pull request #1
Opened 2023-02-27 17:17 UTC by vitorcorreasx

Criado FrontEnd com VUEJS e para a API foi usada a lib JSON-SERVER

2023-03-16 11:55 UTC, julianostroschon requested changes
revisar

2023-03-16 11:55 UTC, julianostroschon commented on front/README.md
> +# training
training?

2023-03-16 11:55 UTC, julianostroschon commented on front/src/App.vue
> +  display: flex;
provavelmente desnecessário

2023-03-16 11:55 UTC, julianostroschon commented on front/src/components/Modal.vue
> +})
```suggestion
const props = defineProps({
  isOpen: { 
  type: Boolean,
  default: false
  },  
  modalId: {
  type: String,
  default: () => ''
  }
})
```

2023-03-16 11:55 UTC, julianostroschon commented on front/src/components/Modal.vue
> +  <div :class="[isOpen ? 'modal' : 'hidden']">
não utilize ternário na template, faz uma computed pra isso

2023-03-16 11:55 UTC, julianostroschon commented on front/src/components/Modal.vue
> +  position: absolute;
claramente não tentou direito, quando apela pro `absolute`

2023-03-16 11:55 UTC, julianostroschon commented on front/src/components/Modal.vue
> +.cancel-button {
creio que sejam uma classe só

2023-03-16 11:55 UTC, julianostroschon commented on front/src/components/TaskList.vue
> +  if (value == null || value == " ") {
se foram "    " então é válido?

2023-03-16 11:55 UTC, julianostroschon commented on front/src/helpers/api.js
> +    createTask ($text: String) {
deveria ser obrigatório o tipo String para '$text'

2023-03-16 11:55 UTC, julianostroschon commented on front/src/helpers/api.js
> +    deleteTask($id: Int) {
deve ser obrigatório o tipo Int para '$id'

2023-03-16 11:55 UTC, julianostroschon commented on front/src/helpers/api.js
> +    updateTask($id: Int, $content: String) {
obrigatoriedade dos tipos

2023-03-16 11:55 UTC, julianostroschon commented on front/src/main.js
> +  url: 'http://localhost:64001/'
variável de ambiente

2023-03-16 11:55 UTC, julianostroschon commented on server/package.json
> +    "villus": "^2.2.1"
não precisa existir villus no backend

2023-03-16 11:55 UTC, julianostroschon commented on server/package.json
> +    "apollo-server": "^3.12.0",
qual dos apollos é utilizado?

2023-03-16 11:55 UTC, julianostroschon commented on server/src/database/migrations/20230307161417_create_task_update.js
> +    table.increments('id');
primary?

2023-03-16 11:55 UTC, julianostroschon commented on server/src/database/migrations/20230307161417_create_task_update.js
> +    table.timestamp('updated_at').defaultTo(knex.fn.now())
updated_at com o now()? mas e se a tarefa ainda não foi atualizada?

2023-03-16 11:55 UTC, julianostroschon commented on server/src/models/TaskController.js
> +  async index() {
pq dessa função?

2023-03-16 11:55 UTC, julianostroschon commented on server/src/models/TaskController.js
> +  async index() {
e ainda com esse nome

2023-03-16 11:55 UTC, julianostroschon commented on server/src/models/TaskController.js
> +      console.log(error)
não vai `console` para o repositório

2023-03-16 11:55 UTC, julianostroschon commented on server/src/models/TaskController.js
> +      console.log(error)
console

2023-03-16 11:55 UTC, julianostroschon commented on server/src/server.js
> +    id: Int
nenhuma chave é obrigatória?

2023-03-16 11:55 UTC, julianostroschon commented on server/src/server.js
> +    allTasks: [Task]
obrigatoriedade

2023-03-16 11:55 UTC, julianostroschon commented on server/src/server.js
> +    deleteTask(id: Int): Task
obrigatoriedade dos tipos

2023-03-16 11:55 UTC, julianostroschon commented on server/src/server.js
> +server.listen({port: 64001}).then(({url}) =>{
variável de ambiente

2023-03-20 14:38 UTC, julianostroschon approved these changes

2023-03-20 14:38 UTC, julianostroschon commented on front/src/App.vue
> +  <div>
desnecessária

2023-03-20 14:38 UTC, julianostroschon commented on front/src/App.vue
> +        style="height: 50px; font-size: 1.8em"
não utilizar o style inline

2023-03-20 14:38 UTC, julianostroschon commented on front/src/components/TaskList.vue
> +    alert('Campo vazio')
não utilizar `alert`, criar sua própria forma de notificar

2023-03-20 14:38 UTC, julianostroschon commented on front/src/components/TaskList.vue
> +    refetchTags: ['query'],
boa dica para a reunião semanal

2023-03-20 14:38 UTC, julianostroschon commented on front/src/components/TaskList.vue
> +    <div class="column q-mt-lg">
o comportamento, `column` é nativo das `<div ...>`

2023-03-20 14:38 UTC, julianostroschon commented on front/src/components/TaskList.vue
> +            <q-btn class="q-mr-md q-ml-xl" label="Editar" color="primary" @click="openModal(task.id, task.content)"/>
pq a margem é diferente de um lado para o outro?

2023-03-20 14:38 UTC, julianostroschon commented on server/package.json
> +    "pg": "^8.10.0"
onde tu usa o `pg`?

2023-03-20 14:38 UTC, julianostroschon commented on server/src/models/TaskController.js
> +  async create(req){
quem chama essa função passa parâmetro na primeira posição?

2023-03-20 14:53 UTC, vitorcorreasx commented on server/package.json
> +    "pg": "^8.10.0"
uso ele no knex

2023-03-21 12:36 UTC, merged